/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VirtualStudent;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kishl_000
 */
public class SubjectCutOffForm extends javax.swing.JFrame {

    String sql = "select mean_internals,cutoff from marks where subject=";
    DatabaseStudent db;
    /**
     * Creates new form SubjectCutOffForm
     */
    public SubjectCutOffForm() {
        initComponents();
        db = new DatabaseStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dbs = new javax.swing.JButton();
        maths = new javax.swing.JButton();
        se = new javax.swing.JButton();
        comp = new javax.swing.JButton();
        cnw = new javax.swing.JButton();
        gbr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Mean Of Internals:");

        dbs.setText("DBS");
        dbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbsActionPerformed(evt);
            }
        });

        maths.setText("MATHS");

        se.setText("SE");

        comp.setText("COMP");

        cnw.setText("CNW");

        gbr.setText("GBR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dbs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(se, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gbr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbs)
                    .addComponent(maths))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(se)
                    .addComponent(comp))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gbr)
                    .addComponent(cnw))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbsActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter mean for this semester");
        }
        else
        {
            try {
                sql = sql+"'dbs'";
                System.out.println(sql);
                ResultSet rs=db.stmt.executeQuery(sql);
                
                int MAXN = 10;
                int n = 0;
                double[] x = new double[MAXN];
                double[] y = new double[MAXN];
                double sumx = 0.0, sumy = 0.0, sumx2 = 0.0;
                rs.next();
                while(n < 10) {
                    x[n] = rs.getInt(1);
                    y[n] = rs.getInt(2);
                    sumx  += x[n];
                    sumx2 += x[n] * x[n];
                    sumy  += y[n];
                    n++;
                    rs.next();
                }       double xbar = sumx / n;
                double ybar = sumy / n;
                double xxbar = 0.0, yybar = 0.0, xybar = 0.0;
                for (int i = 0; i < n; i++) {
                    xxbar += (x[i] - xbar) * (x[i] - xbar);
                    yybar += (y[i] - ybar) * (y[i] - ybar);
                    xybar += (x[i] - xbar) * (y[i] - ybar);
                }       double beta1 = xybar / xxbar;
                double beta0 = ybar - beta1 * xbar;
                // print results
                System.out.println("y   = " + beta1 + " * x + " + beta0);
                // analyze results
                int df = n - 2;
                double rss = 0.0;      // residual sum of squares
                double ssr = 0.0;      // regression sum of squares
                for (int i = 0; i < n; i++) {
                    double fit = beta1*x[i] + beta0;
                    rss += (fit - y[i]) * (fit - y[i]);
                    ssr += (fit - ybar) * (fit - ybar);
                }       double R2    = ssr / yybar;
                double svar  = rss / df;
                double svar1 = svar / xxbar;
                double svar0 = svar/n + xbar*xbar*svar1;
                System.out.println("R^2                 = " + R2);
                System.out.println("std error of beta_1 = " + Math.sqrt(svar1));
                System.out.println("std error of beta_0 = " + Math.sqrt(svar0));
                svar0 = svar * sumx2 / (n * xxbar);
                System.out.println("std error of beta_0 = " + Math.sqrt(svar0));
                System.out.println("SSTO = " + yybar);
                System.out.println("SSE  = " + rss);
                System.out.println("SSR  = " + ssr);
                double mean = Integer.parseInt(jTextField1.getText());
                System.out.println("This yr ="+((mean*beta1)+beta0));
            } catch (SQLException ex) {
                System.err.println(ex);
            }
            catch(NumberFormatException ex1) {
                System.err.println(ex1);
                JOptionPane.showMessageDialog(rootPane, "Invalid Number Entered");
            }
            
        }
    }//GEN-LAST:event_dbsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectCutOffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectCutOffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectCutOffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectCutOffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectCutOffForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cnw;
    private javax.swing.JButton comp;
    private javax.swing.JButton dbs;
    private javax.swing.JButton gbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton maths;
    private javax.swing.JButton se;
    // End of variables declaration//GEN-END:variables
}
